phraseapp:
  host: http://localhost:3000/api
  project_id: 1544de7e7f7e828997fc7ef35cde2233
  push:
    sources:
    - file: ./<locale_name>.csv
      params:
        file_format: csv
        format_options:
          key_index: 100
          translation_index: 200
          comment_index: 300
          column_separator: ","
          quote_char: "'"
          enable_pluralization: true
  pull:
    targets:
    - file: ./MessagesBundle_<locale_name>.properties
      params:
        file_format: properties
        format_options:
          escape_single_quotes: false
